//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterClient_WPF.InstrumentLockServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstrumentLockServiceClient.IInstrumentLockService")]
    public interface IInstrumentLockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrumentLockService/Add", ReplyAction="http://tempuri.org/IInstrumentLockService/AddResponse")]
        double Add(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrumentLockService/Add", ReplyAction="http://tempuri.org/IInstrumentLockService/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrumentLockService/intDivide", ReplyAction="http://tempuri.org/IInstrumentLockService/intDivideResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InstrumentLockService.MathFault), Action="http://tempuri.org/IInstrumentLockService/intDivideMathFaultFault", Name="MathFault", Namespace="http://schemas.datacontract.org/2004/07/InstrumentLockService")]
        int intDivide(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrumentLockService/intDivide", ReplyAction="http://tempuri.org/IInstrumentLockService/intDivideResponse")]
        System.Threading.Tasks.Task<int> intDivideAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrumentLockService/getInstrumentLock", ReplyAction="http://tempuri.org/IInstrumentLockService/getInstrumentLockResponse")]
        void getInstrumentLock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrumentLockService/getInstrumentLock", ReplyAction="http://tempuri.org/IInstrumentLockService/getInstrumentLockResponse")]
        System.Threading.Tasks.Task getInstrumentLockAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrumentLockService/getProtocolLock", ReplyAction="http://tempuri.org/IInstrumentLockService/getProtocolLockResponse")]
        void getProtocolLock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrumentLockService/getProtocolLock", ReplyAction="http://tempuri.org/IInstrumentLockService/getProtocolLockResponse")]
        System.Threading.Tasks.Task getProtocolLockAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrumentLockService/getConnectedInfo", ReplyAction="http://tempuri.org/IInstrumentLockService/getConnectedInfoResponse")]
        void getConnectedInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrumentLockService/getConnectedInfo", ReplyAction="http://tempuri.org/IInstrumentLockService/getConnectedInfoResponse")]
        System.Threading.Tasks.Task getConnectedInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInstrumentLockServiceChannel : TesterClient_WPF.InstrumentLockServiceClient.IInstrumentLockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InstrumentLockServiceClient : System.ServiceModel.ClientBase<TesterClient_WPF.InstrumentLockServiceClient.IInstrumentLockService>, TesterClient_WPF.InstrumentLockServiceClient.IInstrumentLockService {
        
        public InstrumentLockServiceClient() {
        }
        
        public InstrumentLockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InstrumentLockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstrumentLockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstrumentLockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double a, double b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double a, double b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public int intDivide(double a, double b) {
            return base.Channel.intDivide(a, b);
        }
        
        public System.Threading.Tasks.Task<int> intDivideAsync(double a, double b) {
            return base.Channel.intDivideAsync(a, b);
        }
        
        public void getInstrumentLock() {
            base.Channel.getInstrumentLock();
        }
        
        public System.Threading.Tasks.Task getInstrumentLockAsync() {
            return base.Channel.getInstrumentLockAsync();
        }
        
        public void getProtocolLock() {
            base.Channel.getProtocolLock();
        }
        
        public System.Threading.Tasks.Task getProtocolLockAsync() {
            return base.Channel.getProtocolLockAsync();
        }
        
        public void getConnectedInfo() {
            base.Channel.getConnectedInfo();
        }
        
        public System.Threading.Tasks.Task getConnectedInfoAsync() {
            return base.Channel.getConnectedInfoAsync();
        }
    }
}
